org: deepaktomar2031
app: serverless-lambda-aws
service: serverless-lambda-aws
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-south-1

functions:
  readAllUsers:
    handler: index.readAllUsers
    events:
      - httpApi:
          path: /users
          method: get
  getUserById:
    handler: index.getUserById
    events:
      - httpApi:
          path: /user/{id}
          method: get
  deleteUserById:
    handler: index.deleteUserById
    events:
      - httpApi:
          path: /user/{id}
          method: delete
  create:
    handler: index.createOrUpdate
    events:
      - httpApi:
          path: /user
          method: post
